/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ab_pgn_dgtboard_DgtBoardInterface */

#ifndef _Included_com_ab_pgn_dgtboard_DgtBoardInterface
#define _Included_com_ab_pgn_dgtboard_DgtBoardInterface
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ab_pgn_dgtboard_DgtBoardInterface_TIMEOUT_MSEC
#define com_ab_pgn_dgtboard_DgtBoardInterface_TIMEOUT_MSEC 300L
/*
 * Class:     com_ab_pgn_dgtboard_DgtBoardInterface
 * Method:    _open
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ab_pgn_dgtboard_DgtBoardInterface__1open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ab_pgn_dgtboard_DgtBoardInterface
 * Method:    _close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ab_pgn_dgtboard_DgtBoardInterface__1close
  (JNIEnv *, jobject);

/*
 * Class:     com_ab_pgn_dgtboard_DgtBoardInterface
 * Method:    _write
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_com_ab_pgn_dgtboard_DgtBoardInterface__1write
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     com_ab_pgn_dgtboard_DgtBoardInterface
 * Method:    _read
 * Signature: ([BIII)I
 */
JNIEXPORT jint JNICALL Java_com_ab_pgn_dgtboard_DgtBoardInterface__1read
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
